version: 2.1
commands:
  install-tfnotify:
    description: tfnotifyのインストール
    steps:
      - run:
          command: |
              wget https://github.com/mercari/tfnotify/releases/download/v0.6.1/tfnotify_linux_amd64.tar.gz
              tar zxvf tfnotify_linux_amd64.tar.gz
              mv tfnotify /usr/local/bin

  run-tfnotify:
    description: tfnotifyの実行
    parameters:
      action:
        type: string
    steps:
      - run:
          name: tfnotifyのインストール
          command: |
            if [ "<< parameters.action >>" = "plan" ]; then
              tfnotify --config .tfnotify/github.yml plan --title "Terraform Plan Output" <"$TFNOTIFY_LOG" >/dev/null || true
            elif [ "<< parameters.action >>" = "apply" ]; then
              tfnotify --config .tfnotify/github.yml apply --title "Terraform Apply Output" <"$TFNOTIFY_LOG" >/dev/null || true
            else
              echo "Invalid action: << parameters.action >>"
              exit 1
            fi


jobs:
  run_terraform_plan:
    docker:
      - image: hashicorp/terraform
    environment:
      TFNOTIFY_LOG: /tmp/tfnotify.log

    steps:
      - checkout
      - install-tfnotify
      - run: terraform init
      - run: terraform validate
      - run: terraform fmt -check -diff -recursive
      - run: terraform plan | tee "$TFNOTIFY_LOG"
      - run-tfnotify:
          action: plan

  run_terraform_apply:
    docker:
      - image: hashicorp/terraform
    environment:
      TFNOTIFY_LOG: /tmp/tfnotify.log

    steps:
      - checkout
      - install-tfnotify
      - run: terraform init
      - run: terraform apply
      - run-tfnotify:
          action: apply

workflows:
  version: 2
  main:
    jobs:
      - run_terraform_plan:
          context: terraform-sample
          filters:
            branches:
              ignore: master

      - run_terraform_apply:
          context: terraform-sample
          filters:
            branches:
              only: master
